export const SHOPPING_CART_PRODUCTS_LOADED = "SHOPPING_CART_PRODUCTS_LOADED";
export const IS_SHOPPING_CART_PRODUCTS_LOADING = "IS_SHOPPING_CART_PRODUCTS_LOADING";
export const PRODUCTS_SHOULD_BE_RELOADED = "PRODUCTS_SHOULD_BE_RELOADED";

