export const PRODUCTS_LOADED = "PRODUCTS_LOADED";

export const PRODUCTS_CREATED = "PRODUCTS_CREATED";

export const PRODUCT_ADDED_TO_CART = "PRODUCTS_ADDED_TO_CART";

export const PRODUCTS_SHOULD_BE_RELOADED = "PRODUCTS_SHOULD_BE_RELOADED";

export const IS_PRODUCTS_LOADING = "IS_PRODUCTS_LOADING";

